### ISSUE TITLE
Could we use `hum` to convert the audio and play it on the fly?

### ISSUE THREAD

**Issue by harryfei** [crbulakites/hum#1]
So cool this project!

I want to use hum to convert the audio and play it on the fly.

eg.
```bash
hum play demo.hum
```
This will improve the compose workflow.

**Comment by crbulakites** [comment]
Thank you for your interest @harryfei! I just started this project, and I am excited to work on it. I will prioritize researching and adding this feature. For the time being until this is implemented, you might be able to get away with using bash to achieve this effect. On my mac I have a command line program called afplay, so it is possible for me to do this:

`hum demo.hum demo.wav; afplay demo.wav`

If you want the afplay process to stay in the background so you don't lose control of your prompt, you can add the ampersand character at the end of the afplay command:

`hum demo.hum demo.wav; afplay demo.wav &`

**Comment by harryfei** [comment]
Ok, thanks.

**Comment by crbulakites** [comment]
Update: I'm planning to add this for the 0.3.0 release.

**Comment by crbulakites** [comment]
This feature has been added with the version 0.3.0 release. Thank you for the recommendation!

**Comment by harryfei** [comment]
@crbulakites I will try.
