### ISSUE TITLE
Question: Have you considered tracker-like notation?

### ISSUE THREAD

**Issue by lf94** [crbulakites/hum#3]
This wouldn't be possible in hum as it would completely change its syntax, but I was just wondering if you've thought about writing notes for a voice in a column instead of a row, like in old-school music trackers. If you're not familiar with trackers here is a modern one https://www.renoise.com/ but many old platforms used to have them too for making music.

Awesome project and I really love the simplicity of the language design. With a powerful text editor I imagine you can get quite a nice workflow going. I plan to at least give it a play tonight :slightly_smiling_face:

**Comment by crbulakites** [comment]
Hi, thank you for your suggestion and interest in the project! I have not been active on GitHub lately, but I will take a look at this later :) If you would like to add an alternative syntax yourself, I encourage you to make a pull request or fork the code, depending on what makes the most sense for your needs!

**Comment by lf94** [comment]
I just wanted to know if you've thought of it - this is not a feature request :slightly_smiling_face:

**Comment by crbulakites** [comment]
I see—I have not thought of it, so I appreciate you bringing it to my attention 🙂
